---
- name: Use runit
  hosts: gocd
  vars:
    - go_services:
      - go-server
      - go-agent
      - go-agent-1
      - go-agent-2
    - go_services_to_start:
      - go-server
      - go-agent

  tasks:
    - apt:
        update_cache: yes
        cache_valid_time: 600

    - apt:
        name: runit
        state: latest

    - stat:
        path: /etc/sv/go-server
      register: go_server_service

    - command: "/etc/init.d/{{item}} stop"
      with_items: go_services
      when: "not go_server_service.stat.exists"

    - service:
        name: "{{item}}"
        enabled: no
      with_items: go_services

    - file:
        path: "/etc/sv/{{item}}"
        state: directory
      with_items: go_services

    - file:
        path: "/etc/sv/{{item}}/log"
        state: directory
      with_items: go_services

    - lineinfile:
        dest: "/etc/default/{{item}}"
        regexp: "^DAEMON="
        line: DAEMON=N
      with_items: go_services

    - copy:
        dest: /etc/sv/go-server/run
        mode: 0755
        content: |
          #!/bin/sh
          DEBIANCONFIG=/etc/default/go-server
          test -f $DEBIANCONFIG && . $DEBIANCONFIG
          cd /var/lib/go-server
          exec 2>&1
          exec chpst -u go /etc/alternatives/java \
          -server \
          -Xms512m \
          -Xmx1024m \
          -XX:PermSize=128m \
          -XX:MaxPermSize=256m \
          -Duser.language=en \
          -Djruby.rack.request.size.threshold.bytes=30000000 \
          -Duser.country=US \
          -Dcruise.config.dir=/etc/go \
          -Dcruise.config.file=/etc/go/cruise-config.xml \
          -Dcruise.server.port=8153 \
          -Dcruise.server.ssl.port=8154 \
          -jar /usr/share/go-server/go.jar

    - copy:
        dest: "/etc/sv/go-agent{{item}}/run"
        mode: 0755
        content: |
          #!/bin/sh
          SERVICE_NAME=go-agent{{item}}
          DEBIANCONFIG=/etc/default/$SERVICE_NAME
          test -f $DEBIANCONFIG && . $DEBIANCONFIG
          exec 2>&1
          exec chpst -u go /usr/share/go-agent{{item}}/agent.sh $SERVICE_NAME
      with_items: ["", "-1", "-2"]

    - copy:
        dest: "/etc/sv/{{item}}/log/run"
        mode: 0755
        content: |
          #!/bin/sh
          exec chpst -u go svlogd /var/log/{{item}}
      with_items: go_services

    - file:
        dest: "/etc/service/{{item}}"
        src: "/etc/sv/{{item}}"
        state: link
      with_items: go_services_to_start

    - runit:
        name: "{{item}}"
        state: started
      with_items: go_services_to_start

